version: "3.5"

services:
  db:
    image: "postgres"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "wheres-my-stuff"
      